# Generated by Django 5.2.4 on 2025-07-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_subscription_coin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Coin",
        ),
    ]
