# Generated by Django 5.2 on 2025-07-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_delete_coin"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllCoinSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=20)),
                ("price", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
