# Generated by Django 5.2 on 2025-07-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_allcoinsnapshot"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AllCoinSnapshot",
        ),
    ]
