# Generated by Django 5.2 on 2025-07-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_delete_allcoinsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="coinsnapshot",
            name="coingecko_id",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
