# Generated by Django 5.2 on 2025-07-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_coinsnapshot_coingecko_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="coinsnapshot",
            name="market_cap",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
