# Generated by Django 5.2 on 2025-07-24 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_coinsnapshot_market_cap"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinDailyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("price", models.FloatField()),
                ("price_change_percent", models.FloatField(blank=True, null=True)),
                ("market_cap", models.BigIntegerField(blank=True, null=True)),
                ("market_cap_change", models.BigIntegerField(blank=True, null=True)),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="subscriptions.coinsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("coin", "date")},
            },
        ),
    ]
