# Generated by Django 5.2.4 on 2025-12-16 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_coindailystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='subscriptions.coinsnapshot')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField()),
                ('sentiment_label', models.CharField(max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.newsarticle')),
            ],
        ),
        migrations.CreateModel(
            name='PriceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_type', models.CharField(max_length=20)),
                ('price_change_percent', models.FloatField()),
                ('price_before', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_after', models.DecimalField(decimal_places=8, max_digits=20)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('news_count', models.IntegerField(default=0)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='subscriptions.coinsnapshot')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('coin', 'date')},
            },
        ),
    ]
