# Generated by Django 5.2.4 on 2025-12-17 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_newsarticle_newssentiment_priceevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='collected_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='news_type',
            field=models.CharField(choices=[('financial', 'Financial'), ('political', 'Political'), ('market', 'Market General'), ('technical', 'Technical Analysis')], default='financial', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.coinsnapshot'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
