# Generated by Django 5.2.4 on 2025-12-17 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_rename_collected_at_newsarticle_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction_date', models.DateField()),
                ('predicted_change_percent', models.FloatField(help_text='Предсказанное изменение цены в %')),
                ('predicted_price', models.DecimalField(decimal_places=8, help_text='Предсказанная цена', max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=8, help_text='Цена на момент прогноза', max_digits=20)),
                ('model_version', models.CharField(default='1.0', max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='subscriptions.coinsnapshot')),
            ],
            options={
                'ordering': ['-prediction_date'],
                'indexes': [models.Index(fields=['coin', '-prediction_date'], name='subscriptio_coin_id_4b2a19_idx')],
                'unique_together': {('coin', 'prediction_date')},
            },
        ),
    ]
