# Generated by Django 5.2.4 on 2025-12-18 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_priceprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(help_text='Дата, на которую делается прогноз')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_direction', models.CharField(choices=[('UP', 'Upward'), ('DOWN', 'Downward')], max_length=4)),
                ('confidence_score', models.FloatField(help_text='Уверенность модели (0-1)')),
                ('probability_up', models.FloatField(help_text='Вероятность роста')),
                ('probability_down', models.FloatField(help_text='Вероятность падения')),
                ('estimated_change_percent', models.FloatField(help_text='Оценка изменения в % (положительное = рост)')),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('estimated_price', models.DecimalField(decimal_places=8, help_text='Оценочная цена на основе направления', max_digits=20)),
                ('model_version', models.CharField(default='classifier_v2', max_length=50)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_predictions', to='subscriptions.coinsnapshot')),
            ],
            options={
                'ordering': ['-prediction_date', '-confidence_score'],
                'indexes': [models.Index(fields=['coin', '-prediction_date'], name='subscriptio_coin_id_3d348a_idx'), models.Index(fields=['predicted_direction'], name='subscriptio_predict_d7768b_idx')],
                'unique_together': {('coin', 'prediction_date')},
            },
        ),
    ]
