# Generated by Django 5.2.4 on 2025-12-18 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_directionprediction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'ordering': ['-last_active'], 'verbose_name': 'Пользователь бота', 'verbose_name_plural': 'Пользователи бота'},
        ),
        migrations.AddField(
            model_name='botuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='language_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='last_active',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='total_commands',
            field=models.IntegerField(default=0, verbose_name='Всего команд'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='total_predictions_viewed',
            field=models.IntegerField(default=0, verbose_name='Просмотров прогнозов'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
    ]
