# Generated by Django 5.2.4 on 2025-12-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0014_alter_botuser_options_botuser_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newssentiment",
            options={
                "verbose_name": "Sentiment анализ",
                "verbose_name_plural": "Sentiment анализы",
            },
        ),
        migrations.AddField(
            model_name="newssentiment",
            name="model_version",
            field=models.CharField(
                default="finbert_v1",
                help_text="Версия модели использованной для анализа",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="newssentiment",
            name="sentiment_label",
            field=models.CharField(max_length=50),
        ),
    ]
