# Generated by Django 5.2.4 on 2025-12-18 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0015_alter_newssentiment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newssentiment",
            options={
                "verbose_name": "FinBERT Sentiment",
                "verbose_name_plural": "FinBERT Sentiments",
            },
        ),
        migrations.RemoveField(
            model_name="newssentiment",
            name="model_version",
        ),
        migrations.CreateModel(
            name="CustomModelSentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentiment_label", models.CharField(max_length=50)),
                ("sentiment_score", models.FloatField()),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "model_version",
                    models.CharField(default="custom_distilbert_v1", max_length=50),
                ),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_sentiments",
                        to="subscriptions.newsarticle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Model Sentiment",
                "verbose_name_plural": "Custom Model Sentiments",
                "unique_together": {("article", "model_version")},
            },
        ),
    ]
